"""Bundle a RunResult into a downloadable ZIP.

Contents:
  main.tf            — full Terraform (as generated/repaired)
  variables.tf       — minimal variable declarations for project_name + region
  README.md          — run summary + assumptions + cost + security findings
  diagram.png|.mmd   — PNG if Graphviz rendered it, else Mermaid fallback
  cost_breakdown.csv — per-resource monthly $
"""
from __future__ import annotations

import csv
import io
import zipfile
from pathlib import Path
from typing import Any


def _readme(result: Any) -> str:
    spec = result.spec
    lines = [
        "# Cloud Architecture — generated bundle",
        "",
        f"**Workload:** {spec.workload_type}  ",
        f"**Scale:** {spec.scale}  ",
        f"**Region:** {spec.region}  ",
        f"**Compliance:** {', '.join(spec.compliance) or '(none)'}  ",
        f"**High availability:** {spec.ha_required}  ",
        f"**Multi-region:** {spec.multi_region}  ",
        "",
        "## Original prompt",
        "",
        f"> {spec.raw_prompt or '(no prompt captured)'}",
        "",
        "## Cost",
        "",
        f"- **Monthly estimate:** ${result.monthly_cost:,.2f} USD",
        f"- **Pricing source:** {result.cost_meta.get('source', 'n/a')} "
        f"(updated {result.cost_meta.get('updated', 'n/a')})",
        "",
    ]
    if result.cost_breakdown:
        lines.append("| Resource | Service | Monthly $ |")
        lines.append("|---|---|---:|")
        for row in result.cost_breakdown:
            lines.append(
                f"| {row.get('name','?')} | {row.get('service','?')} | "
                f"${row.get('monthly_usd', 0):,.2f} |"
            )
        lines.append("")

    lines.append("## Validation")
    lines.append("")
    lines.append(f"- terraform validate: **{'ok' if result.tf_valid else 'FAILED'}** "
                 f"({result.tf_attempts} attempt(s))")
    lines.append(f"- tfsec HIGH/CRITICAL: **{result.tfsec_high}**")
    if result.tfsec_findings:
        lines.append("")
        lines.append("### tfsec findings")
        lines.append("")
        lines.append("| Severity | Rule | Resource | Description |")
        lines.append("|---|---|---|---|")
        for f in result.tfsec_findings:
            desc = (f.get("description") or "").replace("|", "\\|")
            lines.append(
                f"| {f.get('severity','')} | {f.get('rule_id','')} | "
                f"{f.get('resource','')} | {desc} |"
            )
    lines.append("")

    if spec.assumptions:
        lines.append("## Assumptions")
        lines.append("")
        for a in spec.assumptions:
            lines.append(f"- {a}")
        lines.append("")

    if result.explanation:
        lines.append("## Rationale")
        lines.append("")
        lines.append(result.explanation)
        lines.append("")

    lines.append("---")
    lines.append(
        f"_Generated by Cloud Architecture Designer — "
        f"pipeline versions: {result.prompt_versions}_"
    )
    return "\n".join(lines)


def _variables_tf(result: Any) -> str:
    spec = result.spec
    return (
        'variable "project_name" {\n'
        '  type    = string\n'
        f'  default = "{spec.project_name or "cloudarch"}"\n'
        "}\n\n"
        'variable "region" {\n'
        '  type    = string\n'
        f'  default = "{spec.region or "us-east-1"}"\n'
        "}\n"
    )


def _cost_csv(result: Any) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["name", "service", "monthly_usd", "fixed_usd", "usage_usd"])
    for row in result.cost_breakdown:
        w.writerow(
            [
                row.get("name", ""),
                row.get("service", ""),
                row.get("monthly_usd", 0),
                row.get("fixed_usd", 0),
                row.get("usage_usd", 0),
            ]
        )
    return buf.getvalue()


def build_zip(result: Any) -> bytes:
    """Return a zip archive bytestring bundling main.tf + docs + cost CSV."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("main.tf", result.tf_code or "")
        zf.writestr("variables.tf", _variables_tf(result))
        zf.writestr("README.md", _readme(result))
        zf.writestr("cost_breakdown.csv", _cost_csv(result))

        # Diagram: PNG if we have it, Mermaid fallback otherwise.
        if result.diagram_path:
            try:
                png_bytes = Path(result.diagram_path).read_bytes()
                zf.writestr("diagram.png", png_bytes)
            except Exception:
                if result.diagram_mermaid:
                    zf.writestr("diagram.mmd", result.diagram_mermaid)
        elif result.diagram_mermaid:
            zf.writestr("diagram.mmd", result.diagram_mermaid)
    return buf.getvalue()
